from pathlib import Path
from typing import Any, Dict
import re

import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import Font, PatternFill, Border, Side, Alignment
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.utils import get_column_letter


COLUMNS = [
    "Release Version", "Release Date", "Module", "Generated Feature ID",
    "Oracle Feature ID", "Title", "Delivery Status", "Action Required",
    "Business Benefit", "Impact", "Access Requirements", "Bug IDs",
    "Description", "Steps to Enable", "Mandatory (Yes/No)", "URL", "Priority", "Notes"
]


def clean_cell_text(value: Any) -> str:
    text = str(value or "").replace("\r", "\n")
    lines = [line.strip() for line in text.split("\n")]
    cleaned = []
    previous_blank = False
    for line in lines:
        if not line:
            if not previous_blank and cleaned:
                cleaned.append("")
            previous_blank = True
            continue
        cleaned.append(line)
        previous_blank = False
    return "\n".join(cleaned).strip()


def get_feature_prefix(module: str) -> str:
    module_lower = str(module or "").lower()

    if any(x in module_lower for x in ["procure", "sourc", "purch", "contract"]):
        return "PRC"
    if any(x in module_lower for x in ["message", "b2b", "collaboration"]):
        return "MSG"
    if any(x in module_lower for x in ["order", "fulfill"]):
        return "ORM"
    if any(x in module_lower for x in ["manufactur", "production"]):
        return "MFG"
    if any(x in module_lower for x in ["supply chain", "planning"]):
        return "SCP"
    if any(x in module_lower for x in ["product hub", "product information"]):
        return "PIM"
    if any(x in module_lower for x in ["cost", "financial"]):
        return "CST"
    if any(x in module_lower for x in ["warehouse", "inventory", "logistics"]):
        return "INV"
    return "INV"


def _pick(feature: Dict[str, Any], *keys: str, default: str = "") -> str:
    """Pick the first non-empty value from feature dict by key priority."""
    for key in keys:
        value = feature.get(key)
        if value not in (None, "", [], {}):
            return str(value).strip()
    return default


def generate_excel(features: list, output_path: str):
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)

    rows = []

    for idx, feature in enumerate(features, start=1):
        module_name = str(feature.get("module", "")).strip()

        if not module_name or "feature summary" in module_name.lower():
            module_name = "Inventory Management"

        prefix = get_feature_prefix(module_name)
        generated_id = f"{prefix}-{idx:03d}"

        # =========================================================================
        # KEY MAPPING — MUST MATCH ai_enricher.py enriched dict keys EXACTLY
        # =========================================================================
        #
        # ai_enricher.py outputs these keys:
        #   title, url, description, business_benefit, action_required,
        #   impact, steps_to_enable, access_requirements, notes, bug_ids,
        #   oracle_feature_id
        #
        # The FIRST key in each _pick() call MUST be the ai_enricher key.
        # Fallback keys are for backward compatibility with older data sources.
        # =========================================================================

        final_benefit = _pick(
            feature,
            "business_benefit",    # ← ai_enricher key (PRIMARY)
            "benefit",             # ← legacy fallback
            "business_value",      # ← legacy fallback
        )

        # Scrub the legacy internal reviewer note that an earlier build wrote
        # into the customer-facing benefit cell.
        final_benefit = re.sub(
            r"(?i)business value for this feature was not generated by the ai "
            r"pipeline[^.]*\.\s*",
            "",
            str(final_benefit or ""),
        ).strip()

        # HARD GUARANTEE: the Business Benefit column is never blank, whatever
        # happened upstream (AI rate limit, quota error, timeout, malformed
        # response). ai_enricher.ensure_non_empty_benefit() should already have
        # handled this; this is the defence-in-depth layer at the write step.
        if not str(final_benefit or "").strip():
            try:
                from .ai_enricher import ensure_non_empty_benefit
                final_benefit = ensure_non_empty_benefit(
                    "",
                    str(feature.get("title") or ""),
                    str(feature.get("description") or ""),
                    "",
                )
            except Exception as exc:  # never let the guard break the export
                print(f"[EXCEL BENEFIT GUARD] fallback generation failed: {exc}")
                final_benefit = (
                    "Business value for this feature requires functional review."
                )
            print(f"[EXCEL BENEFIT GUARD] Empty benefit for "
                  f"'{feature.get('title')}' — fallback written.")

        final_impact = _pick(
            feature,
            "impact",              # ← ai_enricher key (PRIMARY)
            "business_impact",     # ← legacy fallback
            "impact_analysis",     # ← legacy fallback
        )

        final_description = _pick(
            feature,
            "description",         # ← ai_enricher key (PRIMARY)
            "short_description",   # ← legacy fallback
            "desc",                # ← legacy fallback
        )

        final_steps = _pick(
            feature,
            "steps_to_enable",     # ← ai_enricher key (PRIMARY)
            "steps",               # ← legacy fallback
        )

        final_access = _pick(
            feature,
            "access_requirements", # ← ai_enricher key (PRIMARY)
            "access",              # ← legacy fallback
            "role_information",    # ← legacy fallback
        )

        final_action_required = _pick(
            feature,
            "action_required",     # ← ai_enricher key (PRIMARY)
            default="No Setup Required",
        )

        # Deterministic Mandatory (Yes/No) — set by ai_enricher.assess_mandatory()
        # based on presence of an enable/configuration section on the Oracle
        # page. NOT an AI inference.
        final_mandatory = _pick(
            feature,
            "mandatory",           # ← ai_enricher key (PRIMARY)
            default="Yes",
        )

        rows.append({
            "Release Version": _pick(feature, "release_version", default="26A"),
            "Release Date": _pick(feature, "release_date", default="May 2026"),
            "Module": module_name,
            "Generated Feature ID": generated_id,
            "Oracle Feature ID": _pick(feature, "oracle_feature_id", default="N/A"),
            "Title": clean_cell_text(feature.get("title", "")),
            "Delivery Status": _pick(feature, "delivery_status", default="Enabled"),
            "Action Required": final_action_required,
            "Business Benefit": clean_cell_text(final_benefit),
            "Impact": clean_cell_text(final_impact),
            "Access Requirements": clean_cell_text(final_access),
            "Bug IDs": _pick(feature, "bug_ids", default="None"),
            "Description": clean_cell_text(final_description),
            "Steps to Enable": clean_cell_text(final_steps),
            "Mandatory (Yes/No)": final_mandatory,
            "URL": _pick(feature, "url", "source_url", default=""),
            "Priority": _pick(feature, "priority", default="Medium"),
            "Notes": clean_cell_text(_pick(feature, "notes", default="")),
        })

    df = pd.DataFrame(rows, columns=COLUMNS)
    summary_df = build_summary(df)

    with pd.ExcelWriter(output, engine="openpyxl") as writer:
        df.to_excel(writer, sheet_name="Release Notes", index=False)
        if not summary_df.empty:
            summary_df.to_excel(writer, sheet_name="Summary by Module", index=False)

    style_workbook(output)
    return str(output)


def build_summary(df):
    if df.empty:
        return pd.DataFrame()

    summary = df.groupby("Module").agg(
        Total=("Title", "count"),
        Setup_Required=("Action Required", lambda x: x.isin([
            "Setup Required", "Opt In plus Setup"
        ]).sum()),
        No_Setup=("Action Required", lambda x: x.isin([
            "No Setup Required"
        ]).sum()),
        Opt_In_Required=("Action Required", lambda x: x.isin([
            "Opt In Required", "Opt In plus Setup"
        ]).sum()),
    ).reset_index()

    summary["Action Required Count"] = (
        summary["Setup_Required"] + summary["Opt_In_Required"]
    )

    return summary


def style_workbook(path):
    wb = load_workbook(path)
    ws = wb["Release Notes"]

    header_fill = PatternFill("solid", fgColor="1F4E79")
    header_font = Font(name="Calibri", bold=True, color="FFFFFF", size=11)
    border_style = Border(
        left=Side(style="thin", color="000000"),
        right=Side(style="thin", color="000000"),
        top=Side(style="thin", color="000000"),
        bottom=Side(style="thin", color="000000"),
    )

    # ── Header styling ──
    for cell in ws[1]:
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = border_style

    # ── Column widths (18 columns now with Mandatory (Yes/No)) ──
    widths = [
        15,  # Release Version
        15,  # Release Date
        28,  # Module
        20,  # Generated Feature ID
        18,  # Oracle Feature ID
        45,  # Title
        15,  # Delivery Status
        22,  # Action Required
        55,  # Business Benefit
        55,  # Impact
        40,  # Access Requirements
        15,  # Bug IDs
        55,  # Description
        55,  # Steps to Enable
        18,  # Mandatory (Yes/No)
        35,  # URL
        15,  # Priority
        25,  # Notes
    ]
    for i, width in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = width

    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions

    # ── Data row styling ──
    for row in ws.iter_rows(min_row=2):
        max_lines = 1
        for cell in row:
            cell.font = Font(name="Calibri", size=10)
            cell.alignment = Alignment(wrap_text=True, vertical="top")
            cell.border = border_style

            # ── Conditional formatting by column ──
            col_letter = get_column_letter(cell.column)
            col_header = ws.cell(row=1, column=cell.column).value

            if col_header == "Action Required":
                if cell.value == "No Setup Required":
                    cell.font = Font(name="Calibri", size=10, color="2E7D32")
                elif cell.value == "Setup Required":
                    cell.font = Font(name="Calibri", size=10, color="C62828", bold=True)
                elif "Opt In" in str(cell.value or ""):
                    cell.font = Font(name="Calibri", size=10, color="E65100")

            elif col_header == "Impact":
                val = str(cell.value or "")
                if val.startswith("NO BUSINESS IMPACT"):
                    cell.font = Font(name="Calibri", size=10, color="2E7D32")
                elif val.startswith("MEDIUM IMPACT"):
                    cell.font = Font(name="Calibri", size=10, color="C62828", bold=True)
                elif val.startswith("LOW IMPACT"):
                    cell.font = Font(name="Calibri", size=10, color="E65100")
                elif val.startswith("REVIEW REQUIRED"):
                    cell.font = Font(name="Calibri", size=10, color="6A1B9A", bold=True)

            elif col_header == "Steps to Enable":
                val = str(cell.value or "")
                if val == "No":
                    cell.font = Font(name="Calibri", size=10, color="2E7D32")

            elif col_header == "Mandatory (Yes/No)":
                val = str(cell.value or "")
                if val == "Yes":
                    cell.font = Font(name="Calibri", size=10, color="2E7D32", bold=True)
                elif val == "No":
                    cell.font = Font(name="Calibri", size=10, color="C62828")

            if isinstance(cell.value, str):
                max_lines = max(max_lines, cell.value.count("\n") + 1)

        ws.row_dimensions[row[0].row].height = min(max(35, max_lines * 16), 180)

    # ── Priority dropdown ──
    if ws.max_row > 1:
        priority_col = None
        for cell in ws[1]:
            if cell.value == "Priority":
                priority_col = cell.column
                break
        if priority_col:
            priority_dv = DataValidation(
                type="list",
                formula1='"High,Medium,Low"',
                allow_blank=True,
            )
            ws.add_data_validation(priority_dv)
            priority_dv.add(
                f"{get_column_letter(priority_col)}2:"
                f"{get_column_letter(priority_col)}{ws.max_row}"
            )

    # ── Summary sheet styling ──
    if "Summary by Module" in wb.sheetnames:
        summary_ws = wb["Summary by Module"]
        for cell in summary_ws[1]:
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = Alignment(horizontal="center", vertical="center")
            cell.border = border_style
        for row in summary_ws.iter_rows(min_row=2):
            for cell in row:
                cell.font = Font(name="Calibri", size=10)
                cell.alignment = Alignment(wrap_text=True, vertical="top")
                cell.border = border_style
        for i in range(1, summary_ws.max_column + 1):
            summary_ws.column_dimensions[get_column_letter(i)].width = 25

    wb.save(path)